### ISSUE TITLE
Nice!Nano Latency

### ISSUE THREAD

**Issue by ettercapx86** [jhelvy/wireless-corne#1]
Beautiful creation!
I was curious as to what the experience of input latency is with the Nice!Nano's on the Corne. 

How has your experience been on this build with that?

**Comment by jhelvy** [comment]
Zero latency! It's been fantastic. My only complaint is that ZMK still isn't as feature-packed as QMK at the moment, in particular macros and mousekeys. I use both on my QMK-powered boards, and they're both under development.  When those are complete, this will definitely become my daily driver.
